version: '3.8'
services:
  app:
    build: .
    dockerfile: Dockerfile.publish
    command: mcpo --host 0.0.0.0 --port 8000 --config /app/config.json
    ports:
      - "8000:8000"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true